configs:
  cm:
    accounts.image-updater: apiKey
    timeout.reconciliation: 60s
  rbac:
    policy.csv: |
      p, role:image-updater, applications, get, */*, allow
      p, role:image-updater, applications, update, */*, allow
      g, image-updater, role:image-updater
    policy.default: role.readonly
redis-ha:
  enabled: false
controller:
  replicas: 1
server:
  autoscaling:
    enabled: false
    minReplicas: 1
repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1
applicationSet:
  replicaCount: 1